AWSTemplateFormatVersion: '2010-09-09'
Description: 'Deployment bucket for Simple REST API application deployed on EC2 with public IP'

Parameters:

  BucketName:
    Type: String
    Description: S3 Bucket name for application data
    Default: simplerestapi-bucket-20251016


Resources:
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private
      Tags:
        - Key: Name
          Value: !Ref BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
            BucketKeyEnabled: true
